language: node_js
node_js:
  - '10'
install:
  - npm install
os:
  - linux
stages:
  - test
  - name: deploy
branches:
  only:
    - master
jobs:
  include:
    - stage: test
      script:
        - node --version
        - npm --version
        - echo "Testing Started ..."
        - npm test
        - echo "Testing Finished."
    - stage: deploy
      script:
        - echo "NPM Deploying Started ..."
        - npm version
        - npm run build
        - echo "NPM Building Finished."
        - rm -rf ./npmrc
      deploy:
        provider: npm
        email: silverbulletlee@gmail.com
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
          branch: master
        tag: latest
        condition: '$TRAVIS_TAG =~ ^v(\d+.){2}\d+$'
